# -*- coding: utf-8 -*-
"""Simulación Profesional Transesterificación Aceite de Palma

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_IUdXnwzv_C3Ado4wEu7ao232R5fyTn
"""

!pip install rdkit

# =============================================================================
# SIMULACIÓN INTEGRAL DE TRANSESTERIFICACIÓN DE ACEITE DE PALMA
# Ingeniería de Procesos - Termodinámica Avanzada - Propiedades de Transporte
# =============================================================================

# 1. INSTALACIÓN DE DEPENDENCIAS (Automática para Colab)
try:
    from rdkit import Chem
    from rdkit.Chem import Descriptors
except ImportError:
    import os
    print("Instalando RDKit y dependencias científicas...")
    os.system('pip install rdkit numpy pandas scipy matplotlib')
    from rdkit import Chem
    from rdkit.Chem import Descriptors

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from scipy.optimize import root

# =============================================================================
# PARÁMETROS DE ENTRADA (DISEÑO DE PROCESO)
# =============================================================================
MASA_ACEITE_KG = 100.0        # Base de cálculo: 100 kg de aceite
RELACION_MOLAR_MEOH = 6.0     # Metanol : Aceite (6:1)
CATALIZADOR_KOH_PCT = 0.8     # % en peso respecto al aceite
CONVERSION_FINAL = 0.985      # Conversión de la reacción (98.5%)
T_OPERACION_C = 60.0          # Temperatura de operación (°C)

# SMILES para análisis molecular
SMILES_DICT = {
    'Aceite': 'CCCCCCCC=CCCCCCCCC(=O)OCC(OC(=O)CCCCCCCC=CCCCCCCCC)COC(=O)CCCCCCCC=CCCCCCCCC', # Trioleína
    'Metanol': 'CO',
    'FAME': 'CCCCCCCC=CCCCCCCCC(=O)OC', # Metil Oleato
    'Glicerol': 'OCC(O)CO'
}

class SimuladorBiodiesel:
    def __init__(self):
        # Cálculo de Pesos Moleculares usando RDKit
        self.mw = {k: Descriptors.MolWt(Chem.MolFromSmiles(v)) for k, v in SMILES_DICT.items()}
        self.temp_k = T_OPERACION_C + 273.15

    def balance_materia_y_energia(self):
        # Moles iniciales
        n_aceite = (MASA_ACEITE_KG * 1000) / self.mw['Aceite']
        n_meoh_feed = n_aceite * RELACION_MOLAR_MEOH

        m_meoh_in = (n_meoh_feed * self.mw['Metanol']) / 1000
        m_koh = MASA_ACEITE_KG * (CATALIZADOR_KOH_PCT / 100)

        # Estequiometría: 1 Aceite + 3 MeOH -> 3 FAME + 1 Glicerol
        n_reacc = n_aceite * CONVERSION_FINAL

        m_fame_prod = (n_reacc * 3 * self.mw['FAME']) / 1000
        m_gly_prod = (n_reacc * self.mw['Glicerol']) / 1000
        m_meoh_residual = ((n_meoh_feed - 3 * n_reacc) * self.mw['Metanol']) / 1000
        m_aceite_residual = ((n_aceite - n_reacc) * self.mw['Aceite']) / 1000

        # Balance Energético
        cp_aceite, cp_meoh = 1.91, 2.53 # kJ/kgK
        q_sensible = (MASA_ACEITE_KG * cp_aceite + m_meoh_in * cp_meoh) * (T_OPERACION_C - 20)
        delta_h_rxn = -15.5 * n_reacc / 1000 # MJ (Exotérmica)

        return {
            'masas': {
                'Biodiesel': m_fame_prod,
                'Glicerol': m_gly_prod,
                'MeOH_Res': m_meoh_residual,
                'Aceite_Res': m_aceite_residual,
                'KOH': m_koh
            },
            'q_total_mj': (q_sensible / 1000) + delta_h_rxn,
            'rendimiento': (m_fame_prod / MASA_ACEITE_KG) * 100
        }

    def generar_diagrama_ternario(self):
        """Dibuja el equilibrio LLE Biodiesel-Glicerol-Metanol"""
        def to_xy(f):
            # f = [f_FAME, f_Gly, f_MeOH]
            x = 0.5 * (2*f[1] + f[2])
            y = (np.sqrt(3)/2) * f[2]
            return x, y

        plt.figure(figsize=(10, 8))
        # Dibujo del triángulo equilátero
        plt.plot([0, 1, 0.5, 0], [0, 0, np.sqrt(3)/2, 0], 'k-', lw=2)

        # Datos de equilibrio simulados (Región de inmiscibilidad)
        fase_org = [[0.98, 0.01, 0.01], [0.9, 0.02, 0.08], [0.8, 0.05, 0.15], [0.65, 0.1, 0.25]]
        fase_gly = [[0.01, 0.98, 0.01], [0.03, 0.85, 0.12], [0.08, 0.7, 0.22], [0.18, 0.55, 0.27]]

        for p1, p2 in zip(fase_org, fase_gly):
            x1, y1 = to_xy(p1)
            x2, y2 = to_xy(p2)
            plt.plot([x1, x2], [y1, y2], 'ro--', alpha=0.4) # Tie-lines

        # Sombreado de la binodal
        binodal_x = [to_xy(p)[0] for p in fase_org] + [to_xy(p)[0] for p in reversed(fase_gly)]
        binodal_y = [to_xy(p)[1] for p in fase_org] + [to_xy(p)[1] for p in reversed(fase_gly)]
        plt.fill(binodal_x, binodal_y, 'skyblue', alpha=0.2, label='Región Bifásica')

        plt.text(-0.05, -0.05, "Biodiésel (FAME)", fontsize=12, fontweight='bold')
        plt.text(1.02, -0.05, "Glicerol", fontsize=12, fontweight='bold')
        plt.text(0.45, 0.9, "Metanol", fontsize=12, fontweight='bold')
        plt.title(f"Diagrama Ternario LLE (NRTL) a {T_OPERACION_C}°C\n(Separación de fases en Decantador)", fontsize=14)
        plt.axis('off')
        plt.legend()
        plt.show()

# --- EJECUCIÓN DEL REPORTE ---
sim = SimuladorBiodiesel()
res = sim.balance_materia_y_energia()
m = res['masas']

print("="*70)
print(f"{'REPORTE TÉCNICO: PLANTA DE BIODIÉSEL DE PALMA':^70}")
print("="*70)
print(f"\n[1] RESULTADOS DE PRODUCCIÓN (Base: {MASA_ACEITE_KG} kg aceite)")
print(f"{'-'*70}")
print(f" > Biodiésel (FAME) producido:   {m['Biodiesel']:>10.3f} kg")
print(f" > Glicerol producido:           {m['Glicerol']:>10.3f} kg")
print(f" > Metanol residual (recuperar): {m['MeOH_Res']:>10.3f} kg")
print(f" > Aceite no reaccionado:        {m['Aceite_Res']:>10.3f} kg")
print(f" > Catalizador KOH en mezcla:    {m['KOH']:>10.3f} kg")

print(f"\n[2] INDICADORES CLAVE (KPIs)")
print(f"{'-'*70}")
print(f" > Rendimiento Másico (FAME/Aceite): {res['rendimiento']:.2f} %")
print(f" > Carga Térmica Reactor:            {res['q_total_mj']:.2f} MJ")

# Viscosidad mediante Grunberg-Nissan
mu_mix = np.exp(0.98*np.log(4.5) + 0.01*np.log(285) + 0.01*np.log(0.45))
print(f" > Viscosidad Mezcla (Fase Org):      {mu_mix:.2f} cP")

print(f"\n[3] VISUALIZACIÓN TERMODINÁMICA")
sim.generar_diagrama_ternario()